/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 */

#ifndef PB_MESSAGES_BITCOIN_PB_H_INCLUDED
#define PB_MESSAGES_BITCOIN_PB_H_INCLUDED
#include "pb.h"
#include "messages-common.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _InputScriptType {
    InputScriptType_SPENDADDRESS = 0,
    InputScriptType_SPENDMULTISIG = 1,
    InputScriptType_EXTERNAL = 2,
    InputScriptType_SPENDWITNESS = 3,
    InputScriptType_SPENDP2SHWITNESS = 4
} InputScriptType;
#define _InputScriptType_MIN InputScriptType_SPENDADDRESS
#define _InputScriptType_MAX InputScriptType_SPENDP2SHWITNESS
#define _InputScriptType_ARRAYSIZE ((InputScriptType)(InputScriptType_SPENDP2SHWITNESS+1))

typedef enum _TxRequest_RequestType {
    TxRequest_RequestType_TXINPUT = 0,
    TxRequest_RequestType_TXOUTPUT = 1,
    TxRequest_RequestType_TXMETA = 2,
    TxRequest_RequestType_TXFINISHED = 3,
    TxRequest_RequestType_TXEXTRADATA = 4
} TxRequest_RequestType;
#define _TxRequest_RequestType_MIN TxRequest_RequestType_TXINPUT
#define _TxRequest_RequestType_MAX TxRequest_RequestType_TXEXTRADATA
#define _TxRequest_RequestType_ARRAYSIZE ((TxRequest_RequestType)(TxRequest_RequestType_TXEXTRADATA+1))

typedef enum _TxAck_TransactionType_TxOutputType_OutputScriptType {
    TxAck_TransactionType_TxOutputType_OutputScriptType_PAYTOADDRESS = 0,
    TxAck_TransactionType_TxOutputType_OutputScriptType_PAYTOSCRIPTHASH = 1,
    TxAck_TransactionType_TxOutputType_OutputScriptType_PAYTOMULTISIG = 2,
    TxAck_TransactionType_TxOutputType_OutputScriptType_PAYTOOPRETURN = 3,
    TxAck_TransactionType_TxOutputType_OutputScriptType_PAYTOWITNESS = 4,
    TxAck_TransactionType_TxOutputType_OutputScriptType_PAYTOP2SHWITNESS = 5
} TxAck_TransactionType_TxOutputType_OutputScriptType;
#define _TxAck_TransactionType_TxOutputType_OutputScriptType_MIN TxAck_TransactionType_TxOutputType_OutputScriptType_PAYTOADDRESS
#define _TxAck_TransactionType_TxOutputType_OutputScriptType_MAX TxAck_TransactionType_TxOutputType_OutputScriptType_PAYTOP2SHWITNESS
#define _TxAck_TransactionType_TxOutputType_OutputScriptType_ARRAYSIZE ((TxAck_TransactionType_TxOutputType_OutputScriptType)(TxAck_TransactionType_TxOutputType_OutputScriptType_PAYTOP2SHWITNESS+1))

/* Struct definitions */
typedef struct _Address {
    char address[130];
/* @@protoc_insertion_point(struct:Address) */
} Address;

typedef struct _GetPublicKey {
    pb_size_t address_n_count;
    uint32_t address_n[8];
    bool has_ecdsa_curve_name;
    char ecdsa_curve_name[32];
    bool has_show_display;
    bool show_display;
    bool has_coin_name;
    char coin_name[21];
    bool has_script_type;
    InputScriptType script_type;
/* @@protoc_insertion_point(struct:GetPublicKey) */
} GetPublicKey;

typedef PB_BYTES_ARRAY_T(65) MessageSignature_signature_t;
typedef struct _MessageSignature {
    bool has_address;
    char address[130];
    bool has_signature;
    MessageSignature_signature_t signature;
/* @@protoc_insertion_point(struct:MessageSignature) */
} MessageSignature;

typedef struct _MultisigRedeemScriptType_HDNodePathType {
    HDNodeType node;
    pb_size_t address_n_count;
    uint32_t address_n[8];
/* @@protoc_insertion_point(struct:MultisigRedeemScriptType_HDNodePathType) */
} MultisigRedeemScriptType_HDNodePathType;

typedef struct _PublicKey {
    HDNodeType node;
    bool has_xpub;
    char xpub[113];
/* @@protoc_insertion_point(struct:PublicKey) */
} PublicKey;

typedef PB_BYTES_ARRAY_T(1024) SignMessage_message_t;
typedef struct _SignMessage {
    pb_size_t address_n_count;
    uint32_t address_n[8];
    SignMessage_message_t message;
    bool has_coin_name;
    char coin_name[21];
    bool has_script_type;
    InputScriptType script_type;
/* @@protoc_insertion_point(struct:SignMessage) */
} SignMessage;

typedef struct _SignTx {
    uint32_t outputs_count;
    uint32_t inputs_count;
    bool has_coin_name;
    char coin_name[21];
    bool has_version;
    uint32_t version;
    bool has_lock_time;
    uint32_t lock_time;
    bool has_expiry;
    uint32_t expiry;
    bool has_overwintered;
    bool overwintered;
    bool has_version_group_id;
    uint32_t version_group_id;
    bool has_timestamp;
    uint32_t timestamp;
    bool has_branch_id;
    uint32_t branch_id;
/* @@protoc_insertion_point(struct:SignTx) */
} SignTx;

typedef PB_BYTES_ARRAY_T(520) TxAck_TransactionType_TxOutputBinType_script_pubkey_t;
typedef struct _TxAck_TransactionType_TxOutputBinType {
    uint64_t amount;
    TxAck_TransactionType_TxOutputBinType_script_pubkey_t script_pubkey;
    bool has_decred_script_version;
    uint32_t decred_script_version;
/* @@protoc_insertion_point(struct:TxAck_TransactionType_TxOutputBinType) */
} TxAck_TransactionType_TxOutputBinType;

typedef PB_BYTES_ARRAY_T(32) TxRequest_TxRequestDetailsType_tx_hash_t;
typedef struct _TxRequest_TxRequestDetailsType {
    bool has_request_index;
    uint32_t request_index;
    bool has_tx_hash;
    TxRequest_TxRequestDetailsType_tx_hash_t tx_hash;
    bool has_extra_data_len;
    uint32_t extra_data_len;
    bool has_extra_data_offset;
    uint32_t extra_data_offset;
/* @@protoc_insertion_point(struct:TxRequest_TxRequestDetailsType) */
} TxRequest_TxRequestDetailsType;

typedef PB_BYTES_ARRAY_T(73) TxRequest_TxRequestSerializedType_signature_t;
typedef PB_BYTES_ARRAY_T(2048) TxRequest_TxRequestSerializedType_serialized_tx_t;
typedef struct _TxRequest_TxRequestSerializedType {
    bool has_signature_index;
    uint32_t signature_index;
    bool has_signature;
    TxRequest_TxRequestSerializedType_signature_t signature;
    bool has_serialized_tx;
    TxRequest_TxRequestSerializedType_serialized_tx_t serialized_tx;
/* @@protoc_insertion_point(struct:TxRequest_TxRequestSerializedType) */
} TxRequest_TxRequestSerializedType;

typedef PB_BYTES_ARRAY_T(65) VerifyMessage_signature_t;
typedef PB_BYTES_ARRAY_T(1024) VerifyMessage_message_t;
typedef struct _VerifyMessage {
    bool has_address;
    char address[130];
    bool has_signature;
    VerifyMessage_signature_t signature;
    bool has_message;
    VerifyMessage_message_t message;
    bool has_coin_name;
    char coin_name[21];
/* @@protoc_insertion_point(struct:VerifyMessage) */
} VerifyMessage;

typedef PB_BYTES_ARRAY_T(73) MultisigRedeemScriptType_signatures_t;
typedef struct _MultisigRedeemScriptType {
    pb_size_t pubkeys_count;
    MultisigRedeemScriptType_HDNodePathType pubkeys[15];
    pb_size_t signatures_count;
    MultisigRedeemScriptType_signatures_t signatures[15];
    bool has_m;
    uint32_t m;
/* @@protoc_insertion_point(struct:MultisigRedeemScriptType) */
} MultisigRedeemScriptType;

typedef struct _TxRequest {
    bool has_request_type;
    TxRequest_RequestType request_type;
    bool has_details;
    TxRequest_TxRequestDetailsType details;
    bool has_serialized;
    TxRequest_TxRequestSerializedType serialized;
/* @@protoc_insertion_point(struct:TxRequest) */
} TxRequest;

typedef struct _GetAddress {
    pb_size_t address_n_count;
    uint32_t address_n[8];
    bool has_coin_name;
    char coin_name[21];
    bool has_show_display;
    bool show_display;
    bool has_multisig;
    MultisigRedeemScriptType multisig;
    bool has_script_type;
    InputScriptType script_type;
/* @@protoc_insertion_point(struct:GetAddress) */
} GetAddress;

typedef PB_BYTES_ARRAY_T(32) TxAck_TransactionType_TxInputType_prev_hash_t;
typedef PB_BYTES_ARRAY_T(1650) TxAck_TransactionType_TxInputType_script_sig_t;
typedef PB_BYTES_ARRAY_T(32) TxAck_TransactionType_TxInputType_prev_block_hash_bip115_t;
typedef struct _TxAck_TransactionType_TxInputType {
    pb_size_t address_n_count;
    uint32_t address_n[8];
    TxAck_TransactionType_TxInputType_prev_hash_t prev_hash;
    uint32_t prev_index;
    bool has_script_sig;
    TxAck_TransactionType_TxInputType_script_sig_t script_sig;
    bool has_sequence;
    uint32_t sequence;
    bool has_script_type;
    InputScriptType script_type;
    bool has_multisig;
    MultisigRedeemScriptType multisig;
    bool has_amount;
    uint64_t amount;
    bool has_decred_tree;
    uint32_t decred_tree;
    bool has_decred_script_version;
    uint32_t decred_script_version;
    bool has_prev_block_hash_bip115;
    TxAck_TransactionType_TxInputType_prev_block_hash_bip115_t prev_block_hash_bip115;
    bool has_prev_block_height_bip115;
    uint32_t prev_block_height_bip115;
/* @@protoc_insertion_point(struct:TxAck_TransactionType_TxInputType) */
} TxAck_TransactionType_TxInputType;

typedef PB_BYTES_ARRAY_T(80) TxAck_TransactionType_TxOutputType_op_return_data_t;
typedef PB_BYTES_ARRAY_T(32) TxAck_TransactionType_TxOutputType_block_hash_bip115_t;
typedef struct _TxAck_TransactionType_TxOutputType {
    bool has_address;
    char address[130];
    pb_size_t address_n_count;
    uint32_t address_n[8];
    uint64_t amount;
    TxAck_TransactionType_TxOutputType_OutputScriptType script_type;
    bool has_multisig;
    MultisigRedeemScriptType multisig;
    bool has_op_return_data;
    TxAck_TransactionType_TxOutputType_op_return_data_t op_return_data;
    bool has_decred_script_version;
    uint32_t decred_script_version;
    bool has_block_hash_bip115;
    TxAck_TransactionType_TxOutputType_block_hash_bip115_t block_hash_bip115;
    bool has_block_height_bip115;
    uint32_t block_height_bip115;
/* @@protoc_insertion_point(struct:TxAck_TransactionType_TxOutputType) */
} TxAck_TransactionType_TxOutputType;

typedef PB_BYTES_ARRAY_T(1024) TxAck_TransactionType_extra_data_t;
typedef struct _TxAck_TransactionType {
    bool has_version;
    uint32_t version;
    pb_size_t inputs_count;
    TxAck_TransactionType_TxInputType inputs[1];
    pb_size_t bin_outputs_count;
    TxAck_TransactionType_TxOutputBinType bin_outputs[1];
    bool has_lock_time;
    uint32_t lock_time;
    pb_size_t outputs_count;
    TxAck_TransactionType_TxOutputType outputs[1];
    bool has_inputs_cnt;
    uint32_t inputs_cnt;
    bool has_outputs_cnt;
    uint32_t outputs_cnt;
    bool has_extra_data;
    TxAck_TransactionType_extra_data_t extra_data;
    bool has_extra_data_len;
    uint32_t extra_data_len;
    bool has_expiry;
    uint32_t expiry;
    bool has_overwintered;
    bool overwintered;
    bool has_version_group_id;
    uint32_t version_group_id;
    bool has_timestamp;
    uint32_t timestamp;
    bool has_branch_id;
    uint32_t branch_id;
/* @@protoc_insertion_point(struct:TxAck_TransactionType) */
} TxAck_TransactionType;

typedef struct _TxAck {
    bool has_tx;
    TxAck_TransactionType tx;
/* @@protoc_insertion_point(struct:TxAck) */
} TxAck;

/* Default values for struct fields */
extern const char GetPublicKey_coin_name_default[21];
extern const InputScriptType GetPublicKey_script_type_default;
extern const char GetAddress_coin_name_default[21];
extern const InputScriptType GetAddress_script_type_default;
extern const char SignMessage_coin_name_default[21];
extern const InputScriptType SignMessage_script_type_default;
extern const char VerifyMessage_coin_name_default[21];
extern const char SignTx_coin_name_default[21];
extern const uint32_t SignTx_version_default;
extern const uint32_t SignTx_lock_time_default;
extern const uint32_t TxAck_TransactionType_TxInputType_sequence_default;
extern const InputScriptType TxAck_TransactionType_TxInputType_script_type_default;

/* Initializer values for message structs */
#define MultisigRedeemScriptType_init_default    {0, {MultisigRedeemScriptType_HDNodePathType_init_default, MultisigRedeemScriptType_HDNodePathType_init_default, MultisigRedeemScriptType_HDNodePathType_init_default, MultisigRedeemScriptType_HDNodePathType_init_default, MultisigRedeemScriptType_HDNodePathType_init_default, MultisigRedeemScriptType_HDNodePathType_init_default, MultisigRedeemScriptType_HDNodePathType_init_default, MultisigRedeemScriptType_HDNodePathType_init_default, MultisigRedeemScriptType_HDNodePathType_init_default, MultisigRedeemScriptType_HDNodePathType_init_default, MultisigRedeemScriptType_HDNodePathType_init_default, MultisigRedeemScriptType_HDNodePathType_init_default, MultisigRedeemScriptType_HDNodePathType_init_default, MultisigRedeemScriptType_HDNodePathType_init_default, MultisigRedeemScriptType_HDNodePathType_init_default}, 0, {{0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}}, false, 0}
#define MultisigRedeemScriptType_HDNodePathType_init_default {HDNodeType_init_default, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define GetPublicKey_init_default                {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "", false, 0, false, "Bitcoin", false, InputScriptType_SPENDADDRESS}
#define PublicKey_init_default                   {HDNodeType_init_default, false, ""}
#define GetAddress_init_default                  {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "Bitcoin", false, 0, false, MultisigRedeemScriptType_init_default, false, InputScriptType_SPENDADDRESS}
#define Address_init_default                     {""}
#define SignMessage_init_default                 {0, {0, 0, 0, 0, 0, 0, 0, 0}, {0, {0}}, false, "Bitcoin", false, InputScriptType_SPENDADDRESS}
#define VerifyMessage_init_default               {false, "", false, {0, {0}}, false, {0, {0}}, false, "Bitcoin"}
#define MessageSignature_init_default            {false, "", false, {0, {0}}}
#define SignTx_init_default                      {0, 0, false, "Bitcoin", false, 1u, false, 0u, false, 0, false, 0, false, 0, false, 0, false, 0}
#define TxRequest_init_default                   {false, (TxRequest_RequestType)0, false, TxRequest_TxRequestDetailsType_init_default, false, TxRequest_TxRequestSerializedType_init_default}
#define TxRequest_TxRequestDetailsType_init_default {false, 0, false, {0, {0}}, false, 0, false, 0}
#define TxRequest_TxRequestSerializedType_init_default {false, 0, false, {0, {0}}, false, {0, {0}}}
#define TxAck_init_default                       {false, TxAck_TransactionType_init_default}
#define TxAck_TransactionType_init_default       {false, 0, 0, {TxAck_TransactionType_TxInputType_init_default}, 0, {TxAck_TransactionType_TxOutputBinType_init_default}, false, 0, 0, {TxAck_TransactionType_TxOutputType_init_default}, false, 0, false, 0, false, {0, {0}}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define TxAck_TransactionType_TxInputType_init_default {0, {0, 0, 0, 0, 0, 0, 0, 0}, {0, {0}}, 0, false, {0, {0}}, false, 4294967295u, false, InputScriptType_SPENDADDRESS, false, MultisigRedeemScriptType_init_default, false, 0, false, 0, false, 0, false, {0, {0}}, false, 0}
#define TxAck_TransactionType_TxOutputBinType_init_default {0, {0, {0}}, false, 0}
#define TxAck_TransactionType_TxOutputType_init_default {false, "", 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, (TxAck_TransactionType_TxOutputType_OutputScriptType)0, false, MultisigRedeemScriptType_init_default, false, {0, {0}}, false, 0, false, {0, {0}}, false, 0}
#define MultisigRedeemScriptType_init_zero       {0, {MultisigRedeemScriptType_HDNodePathType_init_zero, MultisigRedeemScriptType_HDNodePathType_init_zero, MultisigRedeemScriptType_HDNodePathType_init_zero, MultisigRedeemScriptType_HDNodePathType_init_zero, MultisigRedeemScriptType_HDNodePathType_init_zero, MultisigRedeemScriptType_HDNodePathType_init_zero, MultisigRedeemScriptType_HDNodePathType_init_zero, MultisigRedeemScriptType_HDNodePathType_init_zero, MultisigRedeemScriptType_HDNodePathType_init_zero, MultisigRedeemScriptType_HDNodePathType_init_zero, MultisigRedeemScriptType_HDNodePathType_init_zero, MultisigRedeemScriptType_HDNodePathType_init_zero, MultisigRedeemScriptType_HDNodePathType_init_zero, MultisigRedeemScriptType_HDNodePathType_init_zero, MultisigRedeemScriptType_HDNodePathType_init_zero}, 0, {{0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}}, false, 0}
#define MultisigRedeemScriptType_HDNodePathType_init_zero {HDNodeType_init_zero, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define GetPublicKey_init_zero                   {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "", false, 0, false, "", false, (InputScriptType)0}
#define PublicKey_init_zero                      {HDNodeType_init_zero, false, ""}
#define GetAddress_init_zero                     {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "", false, 0, false, MultisigRedeemScriptType_init_zero, false, (InputScriptType)0}
#define Address_init_zero                        {""}
#define SignMessage_init_zero                    {0, {0, 0, 0, 0, 0, 0, 0, 0}, {0, {0}}, false, "", false, (InputScriptType)0}
#define VerifyMessage_init_zero                  {false, "", false, {0, {0}}, false, {0, {0}}, false, ""}
#define MessageSignature_init_zero               {false, "", false, {0, {0}}}
#define SignTx_init_zero                         {0, 0, false, "", false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define TxRequest_init_zero                      {false, (TxRequest_RequestType)0, false, TxRequest_TxRequestDetailsType_init_zero, false, TxRequest_TxRequestSerializedType_init_zero}
#define TxRequest_TxRequestDetailsType_init_zero {false, 0, false, {0, {0}}, false, 0, false, 0}
#define TxRequest_TxRequestSerializedType_init_zero {false, 0, false, {0, {0}}, false, {0, {0}}}
#define TxAck_init_zero                          {false, TxAck_TransactionType_init_zero}
#define TxAck_TransactionType_init_zero          {false, 0, 0, {TxAck_TransactionType_TxInputType_init_zero}, 0, {TxAck_TransactionType_TxOutputBinType_init_zero}, false, 0, 0, {TxAck_TransactionType_TxOutputType_init_zero}, false, 0, false, 0, false, {0, {0}}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define TxAck_TransactionType_TxInputType_init_zero {0, {0, 0, 0, 0, 0, 0, 0, 0}, {0, {0}}, 0, false, {0, {0}}, false, 0, false, (InputScriptType)0, false, MultisigRedeemScriptType_init_zero, false, 0, false, 0, false, 0, false, {0, {0}}, false, 0}
#define TxAck_TransactionType_TxOutputBinType_init_zero {0, {0, {0}}, false, 0}
#define TxAck_TransactionType_TxOutputType_init_zero {false, "", 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, (TxAck_TransactionType_TxOutputType_OutputScriptType)0, false, MultisigRedeemScriptType_init_zero, false, {0, {0}}, false, 0, false, {0, {0}}, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Address_address_tag                      1
#define GetPublicKey_address_n_tag               1
#define GetPublicKey_ecdsa_curve_name_tag        2
#define GetPublicKey_show_display_tag            3
#define GetPublicKey_coin_name_tag               4
#define GetPublicKey_script_type_tag             5
#define MessageSignature_address_tag             1
#define MessageSignature_signature_tag           2
#define MultisigRedeemScriptType_HDNodePathType_node_tag 1
#define MultisigRedeemScriptType_HDNodePathType_address_n_tag 2
#define PublicKey_node_tag                       1
#define PublicKey_xpub_tag                       2
#define SignMessage_address_n_tag                1
#define SignMessage_message_tag                  2
#define SignMessage_coin_name_tag                3
#define SignMessage_script_type_tag              4
#define SignTx_outputs_count_tag                 1
#define SignTx_inputs_count_tag                  2
#define SignTx_coin_name_tag                     3
#define SignTx_version_tag                       4
#define SignTx_lock_time_tag                     5
#define SignTx_expiry_tag                        6
#define SignTx_overwintered_tag                  7
#define SignTx_version_group_id_tag              8
#define SignTx_timestamp_tag                     9
#define SignTx_branch_id_tag                     10
#define TxAck_TransactionType_TxOutputBinType_amount_tag 1
#define TxAck_TransactionType_TxOutputBinType_script_pubkey_tag 2
#define TxAck_TransactionType_TxOutputBinType_decred_script_version_tag 3
#define TxRequest_TxRequestDetailsType_request_index_tag 1
#define TxRequest_TxRequestDetailsType_tx_hash_tag 2
#define TxRequest_TxRequestDetailsType_extra_data_len_tag 3
#define TxRequest_TxRequestDetailsType_extra_data_offset_tag 4
#define TxRequest_TxRequestSerializedType_signature_index_tag 1
#define TxRequest_TxRequestSerializedType_signature_tag 2
#define TxRequest_TxRequestSerializedType_serialized_tx_tag 3
#define VerifyMessage_address_tag                1
#define VerifyMessage_signature_tag              2
#define VerifyMessage_message_tag                3
#define VerifyMessage_coin_name_tag              4
#define MultisigRedeemScriptType_pubkeys_tag     1
#define MultisigRedeemScriptType_signatures_tag  2
#define MultisigRedeemScriptType_m_tag           3
#define TxRequest_request_type_tag               1
#define TxRequest_details_tag                    2
#define TxRequest_serialized_tag                 3
#define GetAddress_address_n_tag                 1
#define GetAddress_coin_name_tag                 2
#define GetAddress_show_display_tag              3
#define GetAddress_multisig_tag                  4
#define GetAddress_script_type_tag               5
#define TxAck_TransactionType_TxInputType_address_n_tag 1
#define TxAck_TransactionType_TxInputType_prev_hash_tag 2
#define TxAck_TransactionType_TxInputType_prev_index_tag 3
#define TxAck_TransactionType_TxInputType_script_sig_tag 4
#define TxAck_TransactionType_TxInputType_sequence_tag 5
#define TxAck_TransactionType_TxInputType_script_type_tag 6
#define TxAck_TransactionType_TxInputType_multisig_tag 7
#define TxAck_TransactionType_TxInputType_amount_tag 8
#define TxAck_TransactionType_TxInputType_decred_tree_tag 9
#define TxAck_TransactionType_TxInputType_decred_script_version_tag 10
#define TxAck_TransactionType_TxInputType_prev_block_hash_bip115_tag 11
#define TxAck_TransactionType_TxInputType_prev_block_height_bip115_tag 12
#define TxAck_TransactionType_TxOutputType_address_tag 1
#define TxAck_TransactionType_TxOutputType_address_n_tag 2
#define TxAck_TransactionType_TxOutputType_amount_tag 3
#define TxAck_TransactionType_TxOutputType_script_type_tag 4
#define TxAck_TransactionType_TxOutputType_multisig_tag 5
#define TxAck_TransactionType_TxOutputType_op_return_data_tag 6
#define TxAck_TransactionType_TxOutputType_decred_script_version_tag 7
#define TxAck_TransactionType_TxOutputType_block_hash_bip115_tag 8
#define TxAck_TransactionType_TxOutputType_block_height_bip115_tag 9
#define TxAck_TransactionType_version_tag        1
#define TxAck_TransactionType_inputs_tag         2
#define TxAck_TransactionType_bin_outputs_tag    3
#define TxAck_TransactionType_lock_time_tag      4
#define TxAck_TransactionType_outputs_tag        5
#define TxAck_TransactionType_inputs_cnt_tag     6
#define TxAck_TransactionType_outputs_cnt_tag    7
#define TxAck_TransactionType_extra_data_tag     8
#define TxAck_TransactionType_extra_data_len_tag 9
#define TxAck_TransactionType_expiry_tag         10
#define TxAck_TransactionType_overwintered_tag   11
#define TxAck_TransactionType_version_group_id_tag 12
#define TxAck_TransactionType_timestamp_tag      13
#define TxAck_TransactionType_branch_id_tag      14
#define TxAck_tx_tag                             1

/* Struct field encoding specification for nanopb */
extern const pb_field_t MultisigRedeemScriptType_fields[4];
extern const pb_field_t MultisigRedeemScriptType_HDNodePathType_fields[3];
extern const pb_field_t GetPublicKey_fields[6];
extern const pb_field_t PublicKey_fields[3];
extern const pb_field_t GetAddress_fields[6];
extern const pb_field_t Address_fields[2];
extern const pb_field_t SignMessage_fields[5];
extern const pb_field_t VerifyMessage_fields[5];
extern const pb_field_t MessageSignature_fields[3];
extern const pb_field_t SignTx_fields[11];
extern const pb_field_t TxRequest_fields[4];
extern const pb_field_t TxRequest_TxRequestDetailsType_fields[5];
extern const pb_field_t TxRequest_TxRequestSerializedType_fields[4];
extern const pb_field_t TxAck_fields[2];
extern const pb_field_t TxAck_TransactionType_fields[15];
extern const pb_field_t TxAck_TransactionType_TxInputType_fields[13];
extern const pb_field_t TxAck_TransactionType_TxOutputBinType_fields[4];
extern const pb_field_t TxAck_TransactionType_TxOutputType_fields[10];

/* Maximum encoded size of messages (where known) */
#define MultisigRedeemScriptType_size            (2031 + 15*HDNodeType_size)
#define MultisigRedeemScriptType_HDNodePathType_size (54 + HDNodeType_size)
#define GetPublicKey_size                        109
#define PublicKey_size                           (121 + HDNodeType_size)
#define GetAddress_size                          (2112 + 15*HDNodeType_size)
#define Address_size                             133
#define SignMessage_size                         1100
#define VerifyMessage_size                       1250
#define MessageSignature_size                    200
#define SignTx_size                              73
#define TxRequest_size                           2191
#define TxRequest_TxRequestDetailsType_size      52
#define TxRequest_TxRequestSerializedType_size   2132
#define TxAck_size                               (7855 + 1*15*HDNodeType_size + 1*15*HDNodeType_size)
#define TxAck_TransactionType_size               (7849 + 1*15*HDNodeType_size + 1*15*HDNodeType_size)
#define TxAck_TransactionType_TxInputType_size   (3849 + 15*HDNodeType_size)
#define TxAck_TransactionType_TxOutputBinType_size 540
#define TxAck_TransactionType_TxOutputType_size  (2359 + 15*HDNodeType_size)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESSAGES_BITCOIN_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
